services:
  oracle-db:
    image: gvenzl/oracle-free:slim-faststart
    container_name: oracle-free
    environment:
      ORACLE_PASSWORD: senha
    ports:
      - "1521:1521"

  express-app:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Prevent overwriting node_modules
    ports:
      - "3000:3000"
    depends_on:
      - oracle-db
