-- 001-create-users.sql
CREATE TABLE Usuario (
    ID_Usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Email VARCHAR2(100) UNIQUE,
    CPF VARCHAR2(11) UNIQUE,
    Nome VARCHAR2(100), -- TODO: Separar nome e senha
    Senha VARCHAR2(100),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_Usuario),
    CHECK (CPF IS NOT NULL AND LENGTH(CPF) = 11), -- CPF deve ter 11 dígitos
    CHECK (Email IS NOT NULL AND LENGTH(Email) > 0), -- Email não pode ser vazio
    CHECK (Nome IS NOT NULL AND LENGTH(Nome) > 0), -- Nome não pode ser vazio
    CHECK (Senha IS NOT NULL AND LENGTH(Senha) > 0) -- Senha não pode ser vazia
)