-- 002-create-posts.sql
CREATE TABLE Postagem (
    ID_Postagem NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Titulo VARCHAR(100),
    Imagem VARCHAR(255),
    Descricao VARCHAR2(500), -- TODO: Tipos de animal
    Achado_ou_perdido NUMBER(1),
    Ultimo_local_visto VARCHAR2(255), -- TODO: Localizacao
    Data_quando_perdeu DATE,
    ID_Usuario NUMBER,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_Postagem),
    CONSTRAINT FK_Usuario_Postagem FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario)
        ON DELETE CASCADE,
    CHECK (Descricao IS NOT NULL AND LENGTH(Descricao) > 0), -- Descrição não pode ser vazia
    CHECK (Achado_ou_perdido IN (0, 1)), -- Achado ou perdido deve ser 0 ou 1
    CHECK (Ultimo_local_visto IS NOT NULL AND LENGTH(Ultimo_local_visto) > 0), -- Último local visto não pode ser vazio
    CHECK (Data_quando_perdeu IS NOT NULL), -- Data quando perdeu não pode ser nula
    CHECK (ID_Usuario IS NOT NULL) -- ID_Usuario não pode ser nulo
)
-- TODO: Add trigger to Updated_at
;