-- 003-create-comments.sql
CREATE TABLE Comentario (
    ID_Comentario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Conteudo VARCHAR2(500),
    ID_Postagem NUMBER,
    ID_Usuario NUMBER,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_Comentario),
    CONSTRAINT FK_Postagem_Comentario FOREIGN KEY (ID_Postagem) REFERENCES Postagem(ID_Postagem) 
        ON DELETE CASCADE,
    CONSTRAINT FK_Usuario_Comentario FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario) 
        ON DELETE CASCADE,
    CHECK (Conteudo IS NOT NULL AND LENGTH(Conteudo) > 0), -- Conteúdo não pode ser vazio
    CHECK (ID_Postagem IS NOT NULL), -- Postagem_ID não pode ser nulo
    CHECK (ID_Usuario IS NOT NULL) -- Usuario_ID não pode ser nulo
)
-- TODO: Add trigger to Updated_at
;